### ISSUE TITLE
Finish @Reference annotation feature

### ISSUE THREAD

**Issue by jlelse** [afollestad/inquiry#10] opened 2015-12-22 17:31 UTC
I always get following error:

```Gradle
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to serialize object of type [Ljlelse.feedly.Article;
12-22 18:25:06.843 20839-20882/jlelse.readit.debug W/System.err:
at com.afollestad.inquiry.ClassRowConverter.clsToVals(ClassRowConverter.java:360)
12-22 18:25:06.843 20839-20882/jlelse.readit.debug W/System.err:
at com.afollestad.inquiry.Query.run(Query.java:169)
```

And this is the class:

```java
public class Article implements Comparable<Article> {

    public Article() {
    }

    @Column(name = "_id", primaryKey = true, autoIncrement = true)
    public int id;
    @Column
    @Body(name = "id")
    public String articleId;
    @Column
    @Body
    public long published;
    @Body
    public long crawled;
    @Body
    public long updated;
    @Column
    @Body
    public int engagement;
    @Column
    @Body
    public String author;
    @Column
    @Body
    public String title;
    @Column
    @Body(name = "originId")
    public String url;
    @Column
    @Body
    public String[] keywords;
    @Column
    @Body
    public Visual visual;
    @Column
    @Body
    public Origin origin;
    @Column
    @Body
    public Summary summary;

    //Other methods (created for ReadIt)

    @Column
    public String pocketId;
    @Column
    public boolean fromPocket;

    ....

}
```
The @Body annotations are because of Bridge library.

Where's the error?

**Comment by afollestad** [comment] 2015-12-22 17:54
Probably in one of your classes being used for fields (e.g. Visual or Origin)

**Comment by jlelse** [comment] 2015-12-22 18:11
I created all classes like this

**Comment by jlelse** [comment] 2015-12-22 18:12
Ah I think I know why. Do Visual and Origin have to have id integer too?

**Comment by afollestad** [comment] 2015-12-22 18:14
They shouldn't need to.

I actually don't think I've added support for non-primitive, non-String
fields yet.

On Tue, Dec 22, 2015, 12:12 PM Jan-Lk Else <notifications@github.com> wrote:

> Ah I think I know why. Do Visual and Origin have to have id integer too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/inquiry/issues/10#issuecomment-166693668>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by jlelse** [comment] 2015-12-22 18:19
Oh ok then I can't use inquiry

**Comment by afollestad** [comment] 2015-12-22 18:21
Generally you don't put objects directly in tables, you reference other
tables by IDs.

On Tue, Dec 22, 2015, 12:19 PM Jan-Lk Else <notifications@github.com> wrote:

> Oh ok then I can't use inquiry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/inquiry/issues/10#issuecomment-166695534>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment] 2015-12-22 18:22
Serialization of objects into a table is unreliable since deserialization
won't work if you add or remove fields.

On Tue, Dec 22, 2015, 12:21 PM Aidan Follestad <drummer.aidan@gmail.com>
wrote:

> Generally you don't put objects directly in tables, you reference other
> tables by IDs.
>
> On Tue, Dec 22, 2015, 12:19 PM Jan-Lk Else <notifications@github.com>
> wrote:
>
>> Oh ok then I can't use inquiry
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/afollestad/inquiry/issues/10#issuecomment-166695534>.
>>
> --
>
> Regards,
>
> Aidan Follestad
> http://aidanfollestad.com
> 651-528-1662
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment] 2015-12-22 20:17
But this is definitely something important. I wonder what the best way to do it would be.

**Comment by HeinrichReimer** [comment] 2016-01-12 21:47
Maybe a developer can provide a converter of his Object to String and then it could be saved in the database. Maybe somehow like Retrofit does this...

**Comment by afollestad** [comment] 2016-01-12 22:30
Good idea, or even raw `byte[]` data (since SQLite supports blob columns).

**Comment by afollestad** [comment] 2016-01-12 23:47
@jlelse looking back at your original post, that error actually means you did something wrong on your end.

All non-primitive types (all custom classes) need to implement `Serializable` in order to be inserted. That includes all classes which are inside of classes. 

I'll be adding a new mechanism that's faster and more future-proof (since Serializable can cause problems if you add or remove fields from a class after serialization).

**Comment by afollestad** [comment] 2016-01-13 00:50
@jlelse @HeinrichReimer here's what I came up with, it's implemented in the code base now:


**Setup**:

```java
public class Person {

    @Column(autoIncrement = true, name = "_id", primaryKey = true)
    private long mId;
    @Column(name = "name")
    private String mName;
    @Column(name = "age")
    private int mAge;
    @Reference(columnName = "spouse", tableName = "spouses")
    private SimplePerson mSpouse;

    public Person() {
    }

    public Person(String name, int age, SimplePerson spouse) {
        mName = name;
        mAge = age;
        mSpouse = spouse;
    }
}

public static class SimplePerson {

    @Column(autoIncrement = true, name = "_id", primaryKey = true)
    private long mId;
    @Column
    private String mName;

    public SimplePerson() {
    }

    public SimplePerson(String name) {
        mName = name;
    }
}
```

**Insertion**:

```java
SimplePerson oneField = new SimplePerson("Waverly");
Person person = new Person("Aidan", 20, oneField);

Long[] ids = Inquiry.get()
    .insertInto("people", Person.class)
    .values(person)
    .run();
```

**What it does**:

The `@Reference` annotation on the `mSpouse` field tells Inquiry to insert the `SimplePerson` instance into a separate table. The actual value of the column in the `people` table is just an ID referencing the location of the `SimplePerson` in the other table.

**Comment by afollestad** [comment] 2016-01-13 00:51
This is significantly faster than other methods like Serialization because you're not parsing data, you're doing super-fast B+ Tree SQL lookups.

**Comment by afollestad** [comment] 2016-01-13 01:09
https://github.com/afollestad/inquiry/releases/tag/2.1.0

**Comment by afollestad** [comment] 2016-01-13 02:00
Sorry guys, I actually ran into some issues with trying to access two different tables at the same time.

**Comment by jlelse** [comment] 2016-01-13 13:13
I solved this problem using another way of storing the data but nevertheless thank you!

**Comment by HeinrichReimer** [comment] 2016-01-13 14:27
Wow, that's pretty awesome. That way you could store every java `Object` in a database 😵
What would be the expected behavior if the `@Reference` field is an array or `Collection`/`List`?

**Comment by HeinrichReimer** [comment] 2016-01-13 14:44
Thing is I want to save a `Lesson` object in a database and it contains a `List<Subject>` but I can make both `Lesson` and `Subject` insertable by adding `@Column` annotations.

A possible implementation would be to look if the `@Reference`d field is a array, `Collection` or `List` and then instead of saving one reference ID save the reference IDs of all the elements in this collection in order and saving them maybe comma seperated in the original table.

**Comment by HeinrichReimer** [comment] 2016-01-13 16:09
I think you should keep the option to save objects that implement `Serializable` in order to use common classes like `Calendar` in *inquiry*.

**Comment by afollestad** [comment] 2016-01-13 16:33
I haven't added collection/array support yet, but I always have all the
necessary code to do so in Bridge's conversion code luckily.

I think I kept the Serializable support in there but I'll have to double
check later. It's not safe to use Serializable since your app would crash
if you stored an object, modified its class, and tried to load it later.

On Wed, Jan 13, 2016, 10:09 AM Heinrich Reimer <notifications@github.com>
wrote:

> I think you should keep the option to save objects that implement
> Serializable in order to use common classes like Calendar in *inquiry*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/inquiry/issues/10#issuecomment-171344871>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by HeinrichReimer** [comment] 2016-01-13 17:29
@afollestad Thanks for your quick answer! I suppose the java devs at Oracle and Google will always keep the serialization backwards compatible for classes like `Calendar` so I have no doubts to use them.
Great to hear the code is already implemented in *bridge*!

**Comment by afollestad** [comment] 2016-01-13 23:02
@HeinrichReimer very true!

I'll hopefully have this next release ready soon 😬

**Comment by HeinrichReimer** [comment] 2016-01-18 13:39
@afollestad any update on this?

**Comment by afollestad** [comment] 2016-01-18 17:52
I haven't had enough time aside from work

**Comment by HeinrichReimer** [comment] 2016-02-14 21:04
@afollestad How is the progress? I don't want to annoy you and I see you're very busy right now coding _Polar Dashboard_ but I'm really waiting for this feauture to update my app, which many users are requesting... :v:
Can you give me some approximate date when this feature is ready?

**Comment by afollestad** [comment] 2016-02-14 21:06
Oh sorry I almost forgot about this!

Yeah, I've been busy with Polar on the weekend and busy with mobile and server work during the week (for my job), but I'll try to get back to this soon. 

I actually hit a block with this issue last time I was working on it that prevented me from finishing it, I can't remember what it was now.

**Comment by HeinrichReimer** [comment] 2016-02-14 21:09
If I can help you, then let me know...

**Comment by HeinrichReimer** [comment] 2016-03-09 06:31
Maybe you can sokve this by using a stack for database operations and by ensuring that all database operations in this stack run sequentially

**Comment by HeinrichReimer** [comment] 2016-03-31 14:15
Is there any chance you could get this working soon? If you don't have enough time then let me know about your initial approach and why it wasn't working, so that I can finish it.

**Comment by HeinrichReimer** [comment] 2016-06-01 00:25
This has been fixed in my fork: https://github.com/HeinrichReimer/inquiry/issues/1

**Comment by afollestad** [comment] 2016-06-26 02:10
@HeinrichReimer would you mind sharing what you did to complete this feature?

**Comment by afollestad** [comment] 2016-06-26 02:11
Although there's already so much more than you've added on your end at this point

**Comment by HeinrichReimer** [comment] 2016-07-01 09:22
Yeah, im on vacation currently so I can only describe how I made it.

**Comment by HeinrichReimer** [comment] 2016-07-06 23:59
I followed @afollestad's first approach first and got it working by allowing multiple instances of Inquiry. Than I used a synchronous request from the class row conversion.

**Comment by HeinrichReimer** [comment] 2016-07-07 00:14
One major difference in my approach is that I used some kind of `Converter` structure that automatically chooses the "best" conversion method for saving a specific field to the SQLite database.
For instance a character array could be saved efficiently as `TEXT` and any other class that is annotated as `@Table` could be saved as a reference. That's the second big difference: I decided that it wouldn't be very common to save the same class in different tables as the table's structure would be exactly the same. Therefore it's not necessary to pass the table name to each of Inquiry's calls. I simply added the `@Table` annotation to store that information directly in each insertable class.

**Comment by HeinrichReimer** [comment] 2016-07-07 00:19
I'm not quite sure if we should create a pull request from my fork because it has quite a bunch of breaking changes. But that's your decision, @afollestad. If you want to merge it, feel free to do so.

**Comment by afollestad** [comment] 2016-08-04 01:17
Done

**Comment by afollestad** [comment] 2016-08-04 01:17
(Finished it on my end)

**Closed by afollestad** 2016-08-04 01:17 UTC
Labels: enhancement

**Comment by afollestad** [comment] 2016-08-04 01:26
https://github.com/afollestad/inquiry/releases/tag/3.0.0
